#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
new_str="return 301 tech-novice://return_me permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx start
